#!/bin/bash

#
#	LusionCP Install Script
#	V1.6 A4
#

# Variables
CLIENTPROC = "https://www.lusioncp.me/lcpdev/client_install.php"
DOWNLOAD = "https://www.lusioncp.me/download/"
LIBNAMEINTEL = "lib-lcp-x86.tar.gz"
LIBNAMEAMD = "lib-lcp-x64.tar.gz"
CPUTYPE = $(uname -m)
SQLFILE = "./.lcpsql"

# Function for fetching the data
download() {
	fetch --no-verify-peer $1
}

# This makes the 1% of installation
# (originally for testing the API)
echo 'export BATCH=yes' >> ~/.bash_profile
download $CLIENTPROC'?action=install_percent&percent=1'

# This makes 15% of installation
# Getting the 'free' command written in perl
download http://www.cyberciti.biz/files/scripts/freebsd-memory.pl.txt
mv freebsd-memory.pl.txt /usr/local/bin/free
chmod +x /usr/local/bin/free
download $CLIENTPROC'?action=install_percent&percent=15'

# Ports management rounds up to 50% of installation process
portsnap --interactive fetch extract
portsnap --interactive fetch update
pkg update
pkg upgrade -y

download $CLIENTPROC'?action=install_percent&percent=50'

# MariaDB requests make config if SSL installed
# So we remove it
cd /usr/ports/security/openssl && make deinstall

# We install MariaDB Server
# A replacement for MySQL (which requires make config !!!)
pkg install -y databases/mariadb55-server
echo 'mysql_enable="YES"' >> /etc/rc.conf

download $CLIENTPROC'?action=install_percent&percent=75'

cd /usr
if [ $CPUTYPE  ==  "amd64" ]; then
	download $DOWNLOAD$LIBNAMEAMD
	tar -zxvf $LIBNAMEAMD
	rm $LIBNAMEAMD
elif [ $CPUTYPE == "i386" ]; then
    download $DOWNLOAD$LIBNAMEINTEL
	tar -zxvf $LIBNAMEINTEL
	rm $LIBNAMEINTEL
fi

# Here we write MySQL informations to a file
# Setting a password to root user from API
# This will be 82%
cd /root
echo 'user: root' >> $SQLFILE
download $CLIENTPROC'?action=get_random_password'
mv *'?action=get_random_password' rand_passwd
cat rand_passwd >> $SQLFILE

# Here we setup the root password get from local .lcpsql file
download $CLIENTPROC'?action=send_secure_mysql'

download $CLIENTPROC'?action=install_percent&percent=82'

#Finishing up the rest
rm client_*

download $CLIENTPROC'?action=install_percent&percent=100'
download $CLIENTPROC'?action=update_status'
