#!/bin/bash

#
#	LusionCP Install Script
#	V1.6 A1
#

# Variables
CLIENTPROC = "https://www.lusioncp.me/lcpdev/client_install.php"
DOWNLOAD = "https://www.lusioncp.me/download/"
LIBNAMEINTEL = "lib-lcp-x86.tar.gz"
LIBNAMEAMD = "lib-lcp-x64.tar.gz"
CPUTYPE = $(uname -m)

# This makes the 1% of installation
# (originally for testing the API)
echo 'export BATCH=yes' >> ~/.bash_profile
fetch --no-verify-peer -o - $CLIENTPROC'?action=install_percent&percent=1'

# This makes 15% of installation
# Getting the 'free' command written in perl
fetch http://www.cyberciti.biz/files/scripts/freebsd-memory.pl.txt
mv freebsd-memory.pl.txt /usr/local/bin/free
chmod +x /usr/local/bin/free
fetch --no-verify-peer -o - $CLIENTPROC'?action=install_percent&percent=15'

# Ports management rounds up to 50% of installation process
portsnap --interactive fetch extract
portsnap --interactive fetch update
pkg update
pkg upgrade -y

fetch --no-verify-peer -o - $CLIENTPROC'?action=install_percent&percent=50'

# MariaDB requests make config if SSL installed
# So we remove it
cd /usr/ports/security/openssl && make deinstall

# We install MariaDB Server
# A replacement for MySQL (which requires make config !!!)
pkg install -y databases/mariadb55-server
echo 'mysql_enable="YES"' >> /etc/rc.conf

fetch --no-verify-peer -o - $CLIENTPROC'?action=install_percent&percent=75'

cd /usr
if [ $CPUTYPE  ==  "amd64" ]; then
	fetch --no-verify-peer -o - $DOWNLOAD$LIBNAMEAMD
	tar -zxvf $LIBNAMEAMD
	rm $LIBNAMEAMD
elif [ $CPUTYPE == "i386" ]; then
    fetch --no-verify-peer -o - $DOWNLOAD$LIBNAMEINTEL
	tar -zxvf $LIBNAMEINTEL
	rm $LIBNAMEINTEL
fi
fetch --no-verify-peer -o - $CLIENTPROC'?action=install_percent&percent=100'
fetch --no-verify-peer -o - $CLIENTPROC'?action=update_status'

rm client_*
