#!/bin/bash

#
# LusionCP Pre-Installation script
# Version: 1.0 a1
#

#
# Currently supported OS:
#
#   FreeBSD 10, FreeBSD 9
#

# Function for fetching the data
CLIENTPROC="https://www.lusioncp.me/lcpdev/client_install.php"
download() {
  fetch --no-verify-peer "$1" -output="$2"
}

update_procent() {
  fetch --no-verify-peer "$CLIENTPROC?action=install_percent&percent=$1"
}

LCPROOT="/root/lcp"
VERSION="uname -r | cut -c1"

# Checking if FreeBSD or not
if [ "$(uname -s)" == 'FreeBSD' ]; then
  type='bsd'
fi

# TODO: check FreeBSD version

if [ "$VERSION" != '8' -a  "$VERSION" != '1' -a "$VERSION" != 9 ]; then
  echo 'Error: currently only FreeBSD 9 or 10 is supported'
  exit 1
fi

# This makes the 1% of installation
# (originally for testing the API)
echo 'export BATCH=yes' >> /root/.bash_profile
mkdir lcp && cd lcp
mkdir tmp && chmod -R 0777 tmp
mkdir install
mkdir backup
touch setup.log
cd $LCPROOT/install
update_procent 1
cd $LCPROOT

fetch --no-verify-peer https://www.lusioncp.me/download/lcp-install-$type
chmod +x lcp-install-$type
sh lcp-install-$type > $LCPROOT/setup.log
