#!/bin/bash

#
#	LusionCP Install Script
#	V1.7 Beta
#

# Variables
CLIENTPROC = "https://www.lusioncp.me/lcpdev/client_install.php"
DOWNLOAD = "https://www.lusioncp.me/download/"
LIBNAMEINTEL = "lib-lcp-x86.tar.gz"
LIBNAMEAMD = "lib-lcp-x64.tar.gz"
CPUTYPE = $(uname -m)
SQLFILE = ".lcpsql"
LCPROOT = "/root/lcp"

# Function for fetching the data
download() {
	fetch --no-verify-peer $1 -output=$2
}

download https://www.lusioncp.me/download/lcp-install-bsd

# This makes 15% of installation
# Getting the 'free' command written in perl
download http://www.cyberciti.biz/files/scripts/freebsd-memory.pl.txt free-memory.txt
cp free-memory.txt /usr/local/bin/free
chmod +x /usr/local/bin/free
cd $LCPROOT/install
download $CLIENTPROC'?action=install_percent&percent=15' install.15
cd $LCPROOT

# Ports management rounds up to 50% of installation process
portsnap --interactive fetch extract
portsnap --interactive fetch update
pkg update
pkg upgrade -y

cd $LCPROOT/install
download $CLIENTPROC'?action=install_percent&percent=50' install.50
cd $LCPROOT

# MariaDB requests make config if SSL installed
# So we remove it
cd /usr/ports/security/openssl && make deinstall

# We install MariaDB Server
# A replacement for MySQL (which requires make config !!!)
pkg install -y databases/mariadb55-server
#echo 'mysql_enable="YES"' >> /etc/rc.conf
# Cleaner method to set MySQL to RC
/usr/local/etc/rc.d/mysql-server rcvar >> /etc/rc.conf

cd $LCPROOT/install
download $CLIENTPROC'?action=install_percent&percent=75' install.75
cd $LCPROOT

cd /usr
if [ $CPUTYPE  ==  "amd64" ]; then
	download $DOWNLOAD$LIBNAMEAMD
	tar -zxvf $LIBNAMEAMD
	rm $LIBNAMEAMD
elif [ $CPUTYPE == "i386" ]; then
    download $DOWNLOAD$LIBNAMEINTEL
	tar -zxvf $LIBNAMEINTEL
	rm $LIBNAMEINTEL
fi

# TODO: fixme
# Checking if MySQL Service is up and running
cd $LCPROOT
if [ ps ax | grep -v grep | grep mysql > /dev/null ];
then
	echo "MySQL is running, no start required" >> $LCPROOT/setup.log
else
	echo "MySQL is not running. Starting up" >> $LCPROOT/setup.log
	service mysql-server start
fi

# Here we write MySQL informations to a file
# Setting a password to root user from API
cd $LCPROOT
echo 'user: root' >> $LCPROOT/$SQLFILE
cd $LCPROOT/install
download $CLIENTPROC'?action=get_random_password' install.80
cat install.80 >> $SQLFILE

# Here we setup the root password get from local .lcpsql file
download $CLIENTPROC'?action=send_secure_mysql' install.81

download $CLIENTPROC'?action=install_percent&percent=100' install.99
download $CLIENTPROC'?action=update_status' install.100
